import turtle
t = turtle.Turtle()
t.speed(0)

cube = 50

def ITetrimino():
    t.goto(0,0)
    t.begin_fill()
    t.color('cyan')
    for i in range(2):
        t.fd(cube*4)
        t.rt(90)
        t.fd(cube)
        t.rt(90)
    t.end_fill()
    t.penup()

def OTetrimino():
    t.goto(200,0)
    t.begin_fill()
    t.color('yellow')
    for i in range(4):
        t.fd(cube*2)
        t.rt(90)
    t.end_fill()
    t.penup()

def TTetrimino():
    t.goto(-150,0)
    t.begin_fill()
    t.color('magenta')
    t.fd(cube*3)
    t.rt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube)
    t.lt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube)
    t.lt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube)
    t.end_fill()
    t.penup()

def LTetrimino():
    t.goto(-150,-150)
    t.begin_fill()
    t.color('orange')
    t.fd(cube*3)
    t.rt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube*2)
    t.lt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube*2)
    t.end_fill()
    t.penup()

def JTetrimino():
    t.goto(150,-200)
    t.begin_fill()
    t.color('blue')
    t.fd(cube*3)
    t.rt(90)
    t.fd(cube*2)
    t.rt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube)
    t.lt(90)
    t.fd(cube*2)
    t.rt(90)
    t.fd(cube)
    t.end_fill()
    t.penup()

def ZTetrimino():
    t.goto(300,300)
    t.begin_fill()
    t.color('red')
    t.fd(cube*2)
    t.rt(90)
    t.fd(cube)
    t.lt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube*2)
    t.rt(90)
    t.fd(cube)
    t.lt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube)
    t.end_fill()
    t.penup()

def STetrimino():
    t.goto(-300,300)
    t.begin_fill()
    t.color('green')
    t.fd(cube*2)
    t.rt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube)
    t.lt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube*2)
    t.rt(90)
    t.fd(cube)
    t.rt(90)
    t.fd(cube)
    t.lt(90)
    t.fd(cube)
    t.end_fill()
    t.penup()

def toutTracer():
    ITetrimino()
    OTetrimino()
    TTetrimino()
    LTetrimino()
    JTetrimino()
    ZTetrimino()
    STetrimino()

t.pencolor('black')
